### DISCUSSION TITLE
Document and explain chain type (data structure)

### DISCUSSION THREAD

**Discussion by Spenhouet** [wevm/wagmi#1028] [Ideas]
Starting working with wagmi it seems there is very view documentation and a lot is learning by reading test cases and by trying out.
Wagmi offers very view chain configurations out-of-the-box (more would be helpful as suggested here: https://github.com/wagmi-dev/wagmi/discussions/370). So one needs to define them manually anyway.

To define chain configs one needs to understand the chain type / required data structure.
There seems to be a lot of implicit decision behind the structure that I don't get or/and don't know which ones I need to fulfill and how.
It would be really helpful if there would be a documentation page explaining the chain type.

Looking for existing data on chain configs there is this great project: https://github.com/ethereum-lists/chains
Their chain config data structure is similar but to the same.

I'm trying to convert it but am not sure on some part.

For example the their [config of Ethereum Mainnet](https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1.json):

```json
{
  "name": "Ethereum Mainnet",
  "chain": "ETH",
  "icon": "ethereum",
  "rpc": [
    "https://mainnet.infura.io/v3/${INFURA_API_KEY}",
    "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}",
    "https://api.mycryptoapi.com/eth",
    "https://cloudflare-eth.com"
  ],
  "faucets": [],
  "nativeCurrency": {
    "name": "Ether",
    "symbol": "ETH",
    "decimals": 18
  },
  "infoURL": "https://ethereum.org",
  "shortName": "eth",
  "chainId": 1,
  "networkId": 1,
  "slip44": 60,
  "ens": {
    "registry": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
  },
  "explorers": [
    {
      "name": "etherscan",
      "url": "https://etherscan.io",
      "standard": "EIP3091"
    }
  ]
}
```

While wagmis config of Ethereum looks like that:

```yaml
{
  id: 1,
  name: 'Ethereum',
  network: 'homestead',
  nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  rpcUrls: {
    alchemy: 'https://eth-mainnet.alchemyapi.io/v2',
    default: 'https://eth-mainnet.alchemyapi.io/v2/${defaultAlchemyApiKey}',
    infura: 'https://mainnet.infura.io/v3',
    public: 'https://eth-mainnet.alchemyapi.io/v2/${defaultAlchemyApiKey}',
  },
  blockExplorers: {
    etherscan: {
      name: 'Etherscan',
      url: 'https://etherscan.io',
    },
    default: {
      name: 'Etherscan',
      url: 'https://etherscan.io',
    },
  },
  ens: {
    address: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
  },
  multicall: {
    address: '0xca11bde05977b3631167028862be2a173976ca11',
    blockCreated: 14353601,
  },
}
```

It is not clear which parts need to be "correct" since they are used in wagmi and which parts a just informative.

Some more specific questions:

1. Does the name have any importance? Or just informative?
2. What is the "network" field referring to and what importance does it have? 
3. What is the difference between "public" and "default" in the RPCUrls? They mostly seem to be set to the same value.
4. If I define more RpcUrls, how do I need to name them? Are they even used if I define more? 
5. On the blockExplorers theres mostly "etherscan" and "default" and they again seem to be mostly the same. Is the "etherscan" (or any other custom one) even used for anything or is this all just purely informative?
